eLearningCMS/src/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('registerprovider/', views.RegisterProviderView.as_view(), name='registerprovider'),
    path('password-change/', views.PasswordChangeView.as_view(),
         name='password-change'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password-reset'),
    path('password-reset/done/', views.PasswordResetDoneView.as_view(), name='password-reset-done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
]

eLearningCMS/src/cdn/urls.py
from django.urls import path
from . import views
from rest_framework.schemas import get_schema_view # new

schema_view = get_schema_view(title='Pastebin API') # new

app_name = 'cdn'
urlpatterns = [
    path('schema/', schema_view), # new
    path('getUploadPaths/<int:count>', views.getUploadPaths),
    path('saveLiveSession/<str:videoKey>/<int:chapterId>', views.saveLiveSession),
    path('getSymetricKey', views.getSymetricKey),
    path('saveClientSession/', views.saveClientSession.as_view(), name='saveClientSession'),
    path('logData/', views.saveLogData.as_view(), name='logData'),
    path('getLogData/<int:providerId>/<str:machineName>', views.getLogData),
    path('clientState/', views.saveClientState.as_view(), name='clientState'),
    path('getClientState/<int:providerId>/<str:machineName>', views.getClientState),
    path('fileDetails/', views.saveFileDetails.as_view(), name='fileDetails'),
    path('getFileDetails/<int:providerId>/<str:machineName>', views.getFileDetails),
    path('uploadFile/<int:scheduleId>/<str:machineName>/<str:fileName>', views.postUploadFile),
    path('uploadFileStatus/', views.saveFileUpload.as_view(), name='uploadFileStatus'),
    path('providerStudents/<int:start>/<int:end>/<int:courseid>', views.getProviderStudents),
]

eLearningCMS/src/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('me/', views.ShowProfile.as_view(), name='show_self'),
    path('me/edit/', views.EditProfile.as_view(), name='edit_self'),
    path('<slug:slug>/', views.ShowProfile.as_view(),
         name='show'),
]

eLearningCMS/src/student/urls.py
from django.urls import path
from . import views

app_name = 'student'
urlpatterns = [
     path('', views.showStudentHome.as_view(), name="student_home"),
     path('myCourse', views.myCourses.as_view(), name="my_courses"),
     path('profile', views.StudentProfile.as_view(), name="my_profile"),
     path('recommendation', views.showRecommendedCourses.as_view(), name="recommended_courses"),
     path('progress', views.showProgress.as_view(), name="progress"),
     path('courseDetails/<int:id>', views.courseDetails.as_view(), name="course_details"),
     path('videoDetails/<int:id>', views.sessionDetails.as_view(), name="video_details"),
     path('searchCourse', views.searchCourses.as_view(), name="search_courses"),
     path('verifyEmail/<slug:slug>', views.VerifyEmail.as_view(), name='verify_email'),
     path('view_hours/', views.view_hours.as_view(), name='view_hours')
]

eLearningCMS/src/student/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import *
import provider
from datetime import date

# Create your models here.

class Student(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class StudentDeviceStats(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    deviceinfo = models.CharField(max_length=1000, blank=True)

class StudentPlayStats(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    sessionname = models.CharField(max_length=1000, blank=True)
    lastplayedtime = models.FloatField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    ipaddress = models.CharField(max_length=200, blank=True)
    deviceinfo = models.CharField(max_length=1000, blank=True)
    otherinfo = models.CharField(max_length=1000, blank=True)

eLearningCMS/src/student/forms.py
from __future__ import unicode_literals
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from . import models
import course

eLearningCMS/src/student/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.views.generic.edit import CreateView
from django.shortcuts import redirect
from django.urls import reverse
from collections import OrderedDict
from operator import itemgetter
from django.contrib.auth import get_user_model
from django.http import QueryDict
from django.http import Http404
from . import models
from . import forms
import course
#from course import algos
import provider
import re
import profiles
import payments
import notification
from math import ceil
User = get_user_model()
from schedule.views import isAnyEventLive
from datetime import datetime,timedelta

def getStudent(request):
    studentObj = models.Student.objects.filter(user_id=request.user.id)
    if studentObj.exists():
        return studentObj[0]
    else:
        return studentObj

def getStudentViewAllotedHoursProviderWise(studentid,providerid):
    providerCourses = course.models.Course.objects.filter(provider_id=providerid)
    myCourses = course.models.EnrolledCourse.objects.filter(student_id=studentid,course_id__in=providerCourses.values('id'),active=True)
    if not myCourses:
        return -1,-1
    viewMinutes = 0
    allotedHours = 0
    for c in myCourses:
        allotedHours = max(c.viewhours,allotedHours)
        viewMinutes = viewMinutes + c.completedminutes + c.completedminuteslive
    return int(viewMinutes),allotedHours


class showStudentHome(LoginRequiredMixin, generic.TemplateView):
    template_name = 'student_home.html'
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        notifications = (notification.models.UserNotification.objects.filter(user=request.user.id))
        unseenNotifications = len(notifications.filter(saw=0))
        # set total count of notifications
        kwargs["notificationsCount"] = unseenNotifications
        notifications = notifications.filter(saw=False)
        kwargs["notifications"] = reversed(notifications)
        studentObj = getStudent(request)
        courseIds = course.algos.getEnrolledCourseIds(request)
        myCourses = course.models.EnrolledCourse.objects.filter(student_id=studentObj.id,active=True)
        myCourses = myCourses.filter(course_id__in=courseIds)
        kwargs["courses"] = len(myCourses)
        viewMinutes = 0
        for c in myCourses:
            viewMinutes = viewMinutes + c.completedminutes + c.completedminuteslive
        kwargs["viewMinutes"] = int(viewMinutes)
        
        if isAnyEventLive(request):
            kwargs['live'] = 'on'
        return super().get(request, *args, **kwargs)

class StudentProfile(profiles.views.MyProfile):
    template_name = 'student_profile.html'
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        notifications = (notification.models.UserNotification.objects.filter(user=request.user.id))
        # set total count of notifications
        kwargs["notificationsCount"] = len(notifications)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        super().post(request, *args, **kwargs)
        return redirect("student:my_profile")

class showRecommendedCourses(LoginRequiredMixin, generic.TemplateView):
    template_name = 'recommended_courses.html'
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        studentObj = getStudent(request)
        notJoinedCourses = course.models.Course.objects.raw('SELECT * FROM course_course WHERE published = 1 and public = 1 and id NOT IN (SELECT course_id FROM course_enrolledcourse WHERE student_id = ' + str(studentObj.id) + ') ORDER BY created')
        kwargs["remaining_courses"] = course.algos.getCourseDetailsForCards(request, notJoinedCourses)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        studentObj = getStudent(request)
        courseid = request.POST.get('course')
        courseObj = course.models.Course.objects.filter(id=courseid)[0]

        cart = payments.models.Cart()
        cart.student = studentObj
        cart.course = courseObj

        if "join" in request.POST:
            cart.checkout = True
            cart.save()
            query_dictionary = QueryDict('', mutable=True)
            query_dictionary.update({'id': courseid})
            url = '{base_url}?{querystring}'.format(base_url=reverse("payments:process"),
                                                querystring=query_dictionary.urlencode())
            return redirect(url)

        if "add" in request.POST:
            cart.save()
            url = "payments:my_cart"
            return redirect(url)

class myCourses(LoginRequiredMixin, generic.TemplateView):
    template_name = 'my_courses.html'
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        studentObj = getStudent(request)
        #myCourses = course.models.Course.objects.raw('SELECT * FROM course_course WHERE id IN (SELECT course_id FROM course_enrolledcourse WHERE student_id = ' + str(studentObj.id) + ')')
        myEnrolledCourses = course.models.EnrolledCourse.objects.filter(student_id=studentObj.id,active=True)
        courseIds = course.algos.getEnrolledCourseIds(request)
        myEnrolledCourses = myEnrolledCourses.filter(course_id__in=courseIds)
        myCourses = course.models.Course.objects.filter(id__in=myEnrolledCourses.values('course_id'))
        kwargs["courses"] = course.algos.getCourseDetailsForCards(request, myCourses)
        return super().get(request, *args, **kwargs)

class courseDetails(LoginRequiredMixin, generic.TemplateView):
    template_name = 'course_details.html'
    http_method_names = ['get', 'post']

    def get(self, request, id, *args, **kwargs):
        courseid = id
        courseObj = course.models.Course.objects.filter(id=courseid)[0]
        kwargs["course_detail"] = courseObj

        studentObj = models.Student.objects.filter(user_id=request.user.id)[0]

        sessionsInCourse = provider.models.Session.objects.raw('SELECT * FROM provider_session WHERE id IN (SELECT session_id from course_coursepattern WHERE course_id = ' + str(courseObj.id) + ') ORDER BY uploaded')
        kwargs["included_sessions"] = sessionsInCourse
        courseIds = course.algos.getEnrolledCourseIds(request)
        myEnrolledCourses = course.models.EnrolledCourse.objects.filter(course_id=courseid, student_id=studentObj.id,active=True)
        myEnrolledCourses = myEnrolledCourses.objects.filter(course_id__in=courseIds)
        #present = len(course.models.EnrolledCourse.objects.filter(course_id=courseid, student_id=studentObj.id,active=True))
        present = len(myEnrolledCourses)
        if present == 0:
            kwargs["not_joined"] = True
        return super().get(request, id, *args, **kwargs)

    def post(self, request, id, *args, **kwargs):
        courseid = id
        courseObj = course.models.Course.objects.filter(id=courseid)[0]

        studentObj = models.Student.objects.filter(user_id=request.user.id)[0]
        # sudomain not done
        enrolledCourseObj = course.models.EnrolledCourse()
        enrolledCourseObj.student = studentObj
        enrolledCourseObj.course = courseObj
        enrolledCourseObj.save()

        return redirect("student:course_details", id)

class sessionDetails(LoginRequiredMixin, generic.TemplateView):
    template_name = 'video_details.html'
    http_method_names = ['get']

    def get(self, request, id, *args, **kwargs):
        sessionid = id
        sessionObj = provider.models.Session.objects.filter(id=sessionid)[0]
        kwargs["session_detail"] = sessionObj
        return super().get(request, id, *args, **kwargs)

class searchCourses(LoginRequiredMixin, generic.TemplateView):
    template_name = 'search_courses.html'
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        kwargs["exams"] = course.algos.getExams()
        providerList = User.objects.filter(is_staff=1)
        kwargs["providers"] = providerList
        kwargs["search"] = "Search your Course"
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        searchtext = request.POST.get('search_course')
        exam = request.POST.get('examlist')
        providerstr = request.POST.get('providerlist')
        userObj = User.objects.filter(name=providerstr)[0]
        providerObj = provider.models.Provider.objects.filter(user_id=userObj.id)[0]

        courseList = course.algos.searchCourses(searchtext, providerObj.id, exam)
        examList = course.algos.getExams()
        providerList = User.objects.filter(is_staff=1)
        return render(request, self.template_name, {"courses" : courseList, "exams" : examList, "providers" : providerList, "search" : searchtext})

class showProgress(LoginRequiredMixin, generic.TemplateView):
    template_name = 'progress.html'
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        studentObj = getStudent(request)
        courseDictMap = {}
        courseDictArray = []
        courseDictMap["myCourse"] = False

        enrolledCourseObj = course.models.EnrolledCourse.objects.filter(student_id=studentObj.id,active=True)
        courseIds = course.algos.getEnrolledCourseIds(request)
        enrolledCourseObj = enrolledCourseObj.filter(course_id__in=courseIds)
        if len(enrolledCourseObj) > 0:
            courseDictMap["myCourse"] = True

        for enrolledCourse in enrolledCourseObj:
            courseDict = {}
            courseid = enrolledCourse.course_id
            durationCompleted = 0
            totalDuration = 0
            sessions_list = course.algos.strToIntList(enrolledCourse.sessions)

            for s in sessions_list:
                sessionObj = provider.models.Session.objects.filter(id=s)[0]

eLearningCMS/src/student/templates/__student_base.html
<!DOCTYPE html>
<html lang="en">

  {% load staticfiles %}

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>SB Admin - Start Bootstrap Template</title>
  <!-- Bootstrap core CSS-->
  <link href="{% static 'userDashBoard/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="{% static 'userDashBoard/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href="{% static 'userDashBoard/css/sb-admin.css' %}" rel="stylesheet">
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{% url 'student:my_profile' %}">Welcome {{ user.name }}</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{% url 'student:student_home' %}">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My Courses">
          <a class="nav-link" href="{% url 'student:my_courses' %}">
            <i class="fa fa-fw fa-bookmark-o"></i>
            <span class="nav-link-text">My Courses</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Profile">
          <a class="nav-link" href="{% url 'student:my_profile' %}">
            <i class="fa fa-fw fa-user"></i>
            <span class="nav-link-text">Profile</span>
          </a>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Recommended Courses">
          <a class="nav-link" href="{% url 'student:recommended_courses' %}">
            <i class="fa fa-fw fa-graduation-cap"></i>
            <span class="nav-link-text">Recommended Courses</span>
          </a>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Progress">
          <a class="nav-link" href="{% url 'student:progress' %}">
            <i class="fa fa-fw fa-trophy"></i>
            <span class="nav-link-text">Progress</span>
          </a>
        </li>

      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-envelope"></i>
            <span class="d-lg-none">Messages
              <span class="badge badge-pill badge-primary">12 New</span>
            </span>
            <span class="indicator text-primary d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
          </a>
          <div class="dropdown-menu" aria-labelledby="messagesDropdown">
            <h6 class="dropdown-header">New Messages:</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>David Miller</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>Jane Smith</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>John Doe</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item small" href="#">View all messages</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-bell"></i>
            <span class="d-lg-none">Alerts
              <span class="badge badge-pill badge-warning">6 New</span>
            </span>
            <span class="indicator text-warning d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
          </a>
          <div class="dropdown-menu" aria-labelledby="alertsDropdown">
            <h6 class="dropdown-header">New Alerts:</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong>
                  <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-danger">
                <strong>
                  <i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong>
                  <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item small" href="#">View all alerts</a>
          </div>
        </li>
        <li class="nav-item">
          <form class="form-inline my-2 my-lg-0 mr-lg-2">
            <div class="input-group">
              <input class="form-control" type="text" placeholder="Search Courses...">
              <span class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fa fa-search"></i>
                </button>
              </span>
            </div>
          </form>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">
            <i class="fa fa-fw fa-home"></i></a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      {% block active %}
      <!-- <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="index.html">Dashboard</a>
        </li>
        <li class="breadcrumb-item active"></li>
      </ol> -->
      {% endblock active %}
    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Exam cracker 2018</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="{% url 'accounts:logout' %}">Logout</a>
          </div>
        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'userDashBoard/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'userDashBoard/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'userDashBoard/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'userDashBoard/js/sb-admin.min.js' %}"></script>
  </div>
</body>

</html>

eLearningCMS/src/student/templates/course_details.html
{% extends "__base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block topMainMenu %}
		<div class="top-menu">
			<div class="container">
				<div class="row">
					<div class="col-xs-1">
						<div id="fh5co-logo"><a href="{% url 'home' %}">ExamCracker</a></div>
					</div>
					<div class="col-xs-11 text-right menu-1">
						<ul>
							<li class="active"><a href="{% url 'home' %}">Home</a></li>
							<li><a href="{% url 'courses' %}">Courses</a></li>
							<li><a href="{% url 'pricing' %}">Pricing</a></li>
							<li class="has-dropdown">
								<a href="{% url 'blog' %}">Blog</a>
								<ul class="dropdown">
									<li><a href="#">Web Design</a></li>
									<li><a href="#">eCommerce</a></li>
									<li><a href="#">Branding</a></li>
									<li><a href="#">API</a></li>
								</ul>
							</li>
							<li><a href="{% url 'contact' %}">Contact</a></li>
							{% if user.is_authenticated %}
							    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
								<h1>welcome1 {{ user.name }}</h1>
								{% if user.is_staff %}
								{% else %}
                                    <div class="panel-body">
	                                    <strong>Name</strong>: {{ course_detail.name }}<br>
	                                    <strong>Created On</strong>: {{ course_detail.created }}<br>
	                                    <strong>Exam</strong>: {{ course_detail.exam }}<br>
	                                    <strong>Cost (INR)</strong>: {{ course_detail.cost }}<br>
	                                    <strong>Duration (months)</strong>: {{ course_detail.duration }}<br>
										<strong>Published</strong>: {{ course_detail.published }}<br>
	                                </div>
							        <div class="panel-body">
										<strong>Course Sessions</strong><br>
										{% if included_sessions %}
											<ol>
											    {% for session in included_sessions %}
												    <label for="video"><a href="{% url 'student:video_details' session.id %}">{{ session.name }}</a></label><br>
												{% endfor %}
											</ol>
									    {% endif %}
										{% if not_joined %}
										    <form action="" method="post" enctype="multipart/form-data">
											    {% csrf_token %}
										        <div class="form-group">
                                                    <div class="col-sm-offset-2 col-sm-10">
                                                        <button type="submit" class="btn btn-success">Join</button>
                                                    </div>
                                                </div>
									        </form>
										{% endif %}
									</div>
								{% endif %}
								<p><a href="/logout">Logout</a></p>
							{% else %}
								<li class="btn-cta"><a href="{% url 'accounts:login' %}"><span>Login</span></a></li>
								<li class="btn-cta"><a href="{% url 'accounts:signup' %}"><span>Sign Up</span></a></li>
							{% endif %}
						</ul>
					</div>
				</div>
				
			</div>
		</div>
		{% endblock topMainMenu %}

		{% block container %}
		{% endblock container %}

eLearningCMS/src/student/templates/my_courses.html
{% extends "__user_base.html" %}
{% load staticfiles %}

{% block active %}
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">My Courses</li>
	</ol>
	 

	{% include "__baseCourseTiles.html" with allCourses=courses divId="JoinedCourses" category="My Courses" tilesLimit=":50" %}
									
    
{% endblock active %}

eLearningCMS/src/student/templates/progress.html
{% extends "__user_base.html" %}
{% load staticfiles %}

{% block active %}
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Progress</li>
  </ol>
  <script type="text/javascript" src="{% static 'progress/js/charts/loader.js' %}"></script>
  {% if course_overview.myCourse and not user.is_staff %}
  {% include "piechart.html" with datatoload=course_overview %}
  {% endif %}
{% endblock active %}

eLearningCMS/src/student/templates/recommended_courses.html
{% extends "__user_base.html" %}
{% load staticfiles %}

{% block active %}
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Recommended Courses</li>
  </ol>

  {% include "__baseCourseTiles.html" with allCourses=remaining_courses divId="RecommendedCourses" category="Recommended Courses" tilesLimit=":50" %}
    
{% endblock active %}