eLearningCMS/src/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('registerprovider/', views.RegisterProviderView.as_view(), name='registerprovider'),
    path('password-change/', views.PasswordChangeView.as_view(),
         name='password-change'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password-reset'),
    path('password-reset/done/', views.PasswordResetDoneView.as_view(), name='password-reset-done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
]

eLearningCMS/src/cdn/urls.py
from django.urls import path
from . import views
from rest_framework.schemas import get_schema_view # new

schema_view = get_schema_view(title='Pastebin API') # new

app_name = 'cdn'
urlpatterns = [
    path('schema/', schema_view), # new
    path('getUploadPaths/<int:count>', views.getUploadPaths),
    path('saveLiveSession/<str:videoKey>/<int:chapterId>', views.saveLiveSession),
    path('getSymetricKey', views.getSymetricKey),
    path('saveClientSession/', views.saveClientSession.as_view(), name='saveClientSession'),
    path('logData/', views.saveLogData.as_view(), name='logData'),
    path('getLogData/<int:providerId>/<str:machineName>', views.getLogData),
    path('clientState/', views.saveClientState.as_view(), name='clientState'),
    path('getClientState/<int:providerId>/<str:machineName>', views.getClientState),
    path('fileDetails/', views.saveFileDetails.as_view(), name='fileDetails'),
    path('getFileDetails/<int:providerId>/<str:machineName>', views.getFileDetails),
    path('uploadFile/<int:scheduleId>/<str:machineName>/<str:fileName>', views.postUploadFile),
    path('uploadFileStatus/', views.saveFileUpload.as_view(), name='uploadFileStatus'),
    path('providerStudents/<int:start>/<int:end>/<int:courseid>', views.getProviderStudents),
]

eLearningCMS/src/course/urls.py
from django.urls import path
from . import views
from rest_framework.schemas import get_schema_view # new

schema_view = get_schema_view(title='Pastebin API') # new

app_name = 'course'
urlpatterns = [
     path('coursePage/<int:id>', views.courseDetails.as_view(), name="coursePage"),
     path('addReview/<int:id>', views.addReview.as_view(), name="addReview"),
     path('playSession/<int:chapterid>/<int:sessionid>', views.playSession.as_view(), name="playSession"),
     path('playSessionEnc/<int:chapterid>/<int:sessionid>', views.playSessionEnc.as_view(), name="playSessionEnc"),
     path('updateDurationPlayed/<int:enrolledcourseid>/<int:duration>/<int:live>', views.updateDuration),
     path('updateDurationPlayedProvider/<int:courseid>/<int:duration>', views.updateDurationProvider),
]

eLearningCMS/src/payments/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'payments'

urlpatterns = [
    url(r'^process', views.payment_process.as_view(), name='process'),
    url(r'^done/$', views.payment_done, name='done'),
    url(r'^canceled/$', views.payment_canceled, name='canceled'),
    path('cart', views.Cart.as_view(), name='my_cart'),
    path('addToCart/<int:id>', views.addToCart.as_view(), name='add_to_cart'),
    path('deleteFromCart/<int:id>', views.deleteFromCart.as_view(), name='delete_from_cart'),
]

eLearningCMS/src/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('me/', views.ShowProfile.as_view(), name='show_self'),
    path('me/edit/', views.EditProfile.as_view(), name='edit_self'),
    path('<slug:slug>/', views.ShowProfile.as_view(),
         name='show'),
]

eLearningCMS/src/student/urls.py
from django.urls import path
from . import views

app_name = 'student'
urlpatterns = [
     path('', views.showStudentHome.as_view(), name="student_home"),
     path('myCourse', views.myCourses.as_view(), name="my_courses"),
     path('profile', views.StudentProfile.as_view(), name="my_profile"),
     path('recommendation', views.showRecommendedCourses.as_view(), name="recommended_courses"),
     path('progress', views.showProgress.as_view(), name="progress"),
     path('courseDetails/<int:id>', views.courseDetails.as_view(), name="course_details"),
     path('videoDetails/<int:id>', views.sessionDetails.as_view(), name="video_details"),
     path('searchCourse', views.searchCourses.as_view(), name="search_courses"),
     path('verifyEmail/<slug:slug>', views.VerifyEmail.as_view(), name='verify_email'),
     path('view_hours/', views.view_hours.as_view(), name='view_hours')
]

eLearningCMS/src/course/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.views.generic.edit import CreateView
from django.shortcuts import redirect
from django.urls import reverse
from collections import OrderedDict
from operator import itemgetter
from django.http import QueryDict
from collections import defaultdict
from django.http import Http404
from django.conf import settings
from math import ceil
from django.contrib.auth import get_user_model
from django.forms.models import model_to_dict
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.response import Response
from django.http import JsonResponse
from rest_framework import status
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from . import models
import course
from course import algos
from course import tags
import cdn
import provider
import student
import re
import profiles
import payments
import json
from django.http import HttpResponse
from access.views import parse_user_agents

User = get_user_model()
OFUSCATE_JW = True
# url is https://obfuscator.io/

def getCartCourses(request):
    studentObj = student.views.getStudent(request)
    allCourses = []
    tcost = 0
    if studentObj:
        cartCoursesList = algos.getCartCourses(studentObj)
        for item in cartCoursesList:
            courseDetails = model_to_dict(item)
            providerObj = provider.models.Provider.objects.filter(id=item.provider_id)[0]
            userDetails = algos.getUserNameAndPic(providerObj.user_id)
            courseDetails["provider_name"] = userDetails['name']
            tcost = tcost + int(courseDetails["cost"])
            allCourses.append(courseDetails)
    return tcost,allCourses

# Create your views here.
class fillCartCourses(generic.TemplateView):
    http_method_names = ['get']
    
    def get(self, request, *args, **kwargs):
        tcost,allCourses = getCartCourses(request)
        kwargs["tcost"] = tcost
        kwargs["cartCourses"] = allCourses
        return super().get(request, *args, **kwargs)

def getCourseReview(reviewSummary, userReviewList, courseid):
    reviewObj = course.models.CourseReview.objects.filter(course_id=courseid)
    reviewSummary['star_count'] = range(1, 6)
    reviewSummary['totalReviews'] = len(reviewObj)
    reviewSummary['1'] = 0
    reviewSummary['2'] = 0
    reviewSummary['3'] = 0
    reviewSummary['4'] = 0
    reviewSummary['5'] = 0
    totalRating = 0
    for review in reviewObj:
        if review.rating > 0 and review.rating <= 5:
            reviewSummary[str(review.rating)] += 1
            totalRating += review.rating
            userDetails = algos.getUserNameAndPic(review.student_id)
           
            userDetails['review'] = review.review
            userDetails['rating'] = int(review.rating)
            userDetails['reviewedTime'] = review.reviewed
            
            userReviewList.append(userDetails)

    if totalRating > 0:       
        reviewSummary['averageRating'] = (int(totalRating*10.0/len(reviewObj)))/10.0
        reviewSummary['1Avg'] = str((int(reviewSummary['1']*100.0/len(reviewObj)))) + "%"
        reviewSummary['2Avg'] = str((int(reviewSummary['2']*100.0/len(reviewObj)))) + "%"
        reviewSummary['3Avg'] = str((int(reviewSummary['3']*100.0/len(reviewObj)))) + "%"
        reviewSummary['4Avg'] = str((int(reviewSummary['4']*100.0/len(reviewObj)))) + "%"
        reviewSummary['5Avg'] = str((int(reviewSummary['5']*100.0/len(reviewObj)))) + "%"


class courseDetails(fillCartCourses):
    template_name = 'coursePage.html'
    http_method_names = ['get', 'post']

    def get(self, request, id, *args, **kwargs):
        courseid = id
        courseObj = course.models.Course.objects.filter(id=courseid)

        if len(courseObj) == 0:
            raise Http404()

        courseObj = courseObj[0]
        kwargs["disableKeys"] = "true"
        # this code is for the provider preview.
        # show everything to the provider
        providerObj = provider.models.Provider.objects.filter(user_id=request.user.id)
        checkPublished = True
        courseOverviewMap = {}
        courseOverviewMap["id"] = courseid
        courseOverviewMap["myCourse"] = False

        if providerObj and providerObj[0].id == courseObj.provider_id:
            providerObj = providerObj[0]
            checkPublished = False
            courseOverviewMap["myCourse"] = True
        else:
            providerObj = provider.models.Provider.objects.filter(id=courseObj.provider_id)
            providerObj = providerObj[0]

        if checkPublished and courseObj.published == False:
            kwargs["not_published"] = True
            raise Http404()
     
        #################Get review details########################

        reviewSummary = {}
        #userReviewList = []

        #getCourseReview(reviewSummary, userReviewList, courseid)

        #kwargs['userReviewList'] = userReviewList

        ##########################################################

        
        allowedModules = []
        populateCourseDetails = False
        if request.user.is_authenticated:
            if request.user.is_staff == False:
                studentObj = student.models.Student.objects.filter(user_id=request.user.id)[0]
                enrolledCourse = course.models.EnrolledCourse.objects.filter(student_id=studentObj.id).filter(course_id=courseid,active=True)
                if len(enrolledCourse) > 0:
                    courseOverviewMap["myCourse"] = True
                    reviewSummary["enrolledCourse"] = True

                    # calculate duration completed
                    durationCompleted = 0
                    totalDuration = 0
                    enrolledCourseObj = enrolledCourse[0]
                    if enrolledCourseObj.chapteraccess != '':
                        allowedModules = enrolledCourseObj.chapteraccess.split(',')
                    # check for view hours restriction
                    if enrolledCourseObj.viewhours > 0:
                        courseOverviewMap["viewhours"] = enrolledCourseObj.viewhours
                        courseOverviewMap["completedminutes"] = enrolledCourseObj.completedminutes + enrolledCourseObj.completedminuteslive

                    if enrolledCourseObj.sessions != '':
                        sessionsPlayed = course.algos.strToIntList(enrolledCourseObj.sessions)
                        for s in sessionsPlayed:
                            sessionObj = provider.models.Session.objects.filter(id=s)[0]
                            durationCompleted = durationCompleted + sessionObj.duration
                    populateCourseDetails = True

                    courseDetailMap = algos.getCourseDetails(id,checkPublished,True,allowedModules)
                    kwargs["course_detail"] = courseDetailMap
                    for subj in courseDetailMap:
                        chapters = courseDetailMap[subj]
                        for chapDetails in chapters:
                            for chapId in chapDetails:
                                chapDetail = chapDetails[chapId]
                                totalDuration = totalDuration + chapDetail["duration"]

                    if totalDuration > 0:
                        courseOverviewMap["progress"] = str(ceil(durationCompleted*100/totalDuration)) + '%'
                    else:
                        courseOverviewMap["progress"] = "0%"

                addedCourse = payments.models.Cart.objects.filter(course_id=courseid).filter(student_id=studentObj.id)
                if len(addedCourse) > 0:
                    courseOverviewMap["addedCourse"] = True
        if populateCourseDetails == False:
            courseDetailMap = algos.getCourseDetails(id,checkPublished,True,allowedModules)
            kwargs["course_detail"] = courseDetailMap
        courseOverviewMap["Name"] = courseObj.name
        courseOverviewMap["Description"] = courseObj.description
        courseOverviewMap["Subject"] = courseObj.subjects
        courseOverviewMap["Exam"] = courseObj.exam
        courseOverviewMap["Cost"] = courseObj.cost
        courseOverviewMap["Duration"] = courseObj.duration
        courseOverviewMap["Published"] = courseObj.created
        courseOverviewMap["picture"] = courseObj.picture

        kwargs["course_overview"] = courseOverviewMap
        kwargs['reviewSummary'] = reviewSummary

        kwargs["uploadMaterial"] = False
        kwargs["providerLogo"] = algos.getLogoForProvider(providerObj.user_id)
        planObj = provider.models.Plan.objects.filter(provider_id=courseObj.provider_id)
        if planObj:
            planObj = planObj[0]
            if planObj.uploadMaterial == True:
                kwargs["uploadMaterial"] = True
        return super().get(request, id, *args, **kwargs)

    def post(self, request, id, *args, **kwargs):
        courseid = id
        studentObj = student.models.Student.objects.filter(user_id=request.user.id)[0]
        courseObj = course.models.Course.objects.filter(id=courseid)[0]
        cart = payments.models.Cart()
        cart.student = studentObj
        cart.course = courseObj

        if "join" in request.POST:
            if not settings.COURSE_ENROLLING_ALLOWED:
                return render(request, 'join_block.html')
            cart.checkout = True
            cart.save()
            query_dictionary = QueryDict('', mutable=True)
            query_dictionary.update({'id': courseid})
            url = '{base_url}?{querystring}'.format(base_url=reverse("payments:process"),
                                                querystring=query_dictionary.urlencode())
            return redirect(url)

class playSession(LoginRequiredMixin, generic.TemplateView):
    http_method_names = ['get']
    template_name = 'playSession.html'

eLearningCMS/src/templates/__baseCourseTiles.html
{% load staticfiles %}
{% load thumbnail %}

    <div class="container mt-4">
        <h1 class="text-center mb-3">{{ category }}</h1>
        <div class="row">
            <div class="card-deck">
                {% for currentCourse in allCourses|slice:tilesLimit%}
                <div class="card mb-4" id ="courseCard"style="min-width: 14rem; max-width: 16rem;">
                    {% if user.is_staff and currentCourse.provider_id == provider_id  %}
                        <a href="{% url 'course:coursePage' currentCourse.id %}">
                    {% endif %}
                    <img class="card-img-top" src="{% thumbnail currentCourse.picture 200x180 %}" alt="Card image cap">
                    {% if user.is_staff %}
                        </a> 
                    {% endif %}
                    <div class="card-body" style='background-color:#fcfcfc;' >
                        <div class="container">
                            <div class="row">
                                <div class="col-xs-4 col-sm-4 padding-0" align="left">
                                    <img id="providerPic" src="{% thumbnail currentCourse.profilePic|default:'default_profile.png' 25x25 crop %}" class="rounded-circle" alt="avatar">
                                </div>
                                <div class="single-col-text-8 col-xs-8 col-sm-8 padding-0" align="right">
                                    <i class="fas fa-rupee-sign" aria-hidden="true"></i> 
                                    {{ currentCourse.cost }}
                                </div>
                                <div class="small-text-single-line padding-bottom-0">
                                    {{ currentCourse.provider_name }} 
                                </div>
                            </div>
                                <div align="centre">
                                    <p class="customText" id="firstText"><a style='color:#585858;' href="{% url 'course:coursePage' currentCourse.id %}">{{ currentCourse.name }}: {{ currentCourse.description }} </a></p>
                                    <p class="smallText">{{ currentCourse.exam }} ({{ currentCourse.duration }} months)</p>
                                    <!-- <p class="customText text-center small"> {{ currentCourse.description }} </p> -->
                                </div>
                                <div class="row">
                                <div class="col-xs-4 col-sm-4" align="left">
                                    {% if user.is_staff and currentCourse.provider_id == provider_id  %}
                                        <a style='color:#1f1f1f;' href="{% url 'provider:edit_course' currentCourse.id %}"><i class="far fa-edit"></i></a>
                                    {% elif not user.is_staff and not currentCourse.alreadyEnrolled %}
                                        <a style='color:#1f1f1f;' href="{% url 'payments:add_to_cart' currentCourse.id %}"><i class="fa fa-shopping-cart" title="Add to cart"></i></a>
                                    {% endif %}     
                                </div>
                                {% if user.is_staff and currentCourse.provider_id == provider_id  %}
                                <div class="col-xs-8 col-sm-8" align="right">
                                    <i class="fas fa-graduation-cap" aria-hidden="true"></i> 
                                    {{ currentCourse.enrolledCount }} Student
                                </div>
                                {% elif not user.is_staff and currentCourse.alreadyEnrolled %}
                                <div class="col-xs-8 col-sm-8" align="right">
                                    <i class="fas fa-calendar-alt" aria-hidden="true" title="Expires : mm/dd/yyyy"></i> 
                                    {{ currentCourse.expiry }}
                                </div>
                                {% endif %}   
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>

eLearningCMS/src/templates/_brandname.html
GyaanHive

eLearningCMS/src/templates/about.html
{% extends "__ecBase.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">The Wonderful People Behind the ExamCracker</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="text-center"><!--img class="img-circle centered" <!--src="http://lorempixel.com/128/128/people/9/" alt="profile pic"--></div>
        <!--h1 class="heavy text-center">Iron Man</h1-->
        <h1>Iron Man</h1>
        <h2>Executive</h2>
        <p>From Noida</p>
      </div>
      <div class="col-md-4">
        <div class="text-center"><!--img class="img-circle centered" src="http://lorempixel.com/128/128/people/2/" alt="profile pic"--></div>
        <!--h1 class="heavy text-center">The Hulk</h1-->
        <h1>The Hulk</h1>
        <h2>Executive</h2>
        <p>From Bangalore</p>
      </div>
      <div class="col-md-4">
        <div class="text-center"><!--img class="img-circle centered" src="http://lorempixel.com/128/128/people/1/" alt="profile pic"--></div>
        <!--h1 class="heavy text-center">Thor</h1-->
		<h1>Thor</h1>
        <h2>Executive</h2>
        <p>From Delhi</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2">
  <div class="container">
    <div class="row">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Exam Cracker</strong><br>
            Connaught Place<br>
            Delhi<br>
            India - 110001<br>
            <abbr>P:</abbr> +91 011 222 3333
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(28.631984, 77.218987);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

eLearningCMS/src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_superuser %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
                {% else %}
                  <a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
                  <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Company {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

eLearningCMS/src/templates/debug.html
<!DOCTYPE html>
<html>
<body>
<p> <h1> Logs </h1> </p>
<textarea class="scrollabletextbox" name="logs" cols="100" rows="25">
  {% if log %}
    {{ log.contents }}
  {% endif %}
</textarea>
<p> <h1> Capture File Details </h1> </p>
{% if filedetails %}
    Details : {{ filedetails.details }}
	Time : {{ filedetails.when }}
{% endif %}
<p> <h1> Client State </h1> </p>
{% if clientstate %}
    Time : {{ clientstate.when }}
{% endif %}
<p> <h1> Upload File Details </h1> </p>
{% if fileupload %}
    Time : {{ fileupload.when }}
	Details : {{ fileupload.status }}
{% endif %}
 <form action="" method="post" enctype="multipart/form-data">
   {% csrf_token %}
  <input type="text" name="schedueid" value="Type schedueid" />
  <input type="text" name="filename" value="Type filename" />
  <button type="submit">Submit</button>
</form>
</body>
</html>