eLearningCMS/src/cdn/urls.py
from django.urls import path
from . import views
from rest_framework.schemas import get_schema_view # new

schema_view = get_schema_view(title='Pastebin API') # new

app_name = 'cdn'
urlpatterns = [
    path('schema/', schema_view), # new
    path('getUploadPaths/<int:count>', views.getUploadPaths),
    path('saveLiveSession/<str:videoKey>/<int:chapterId>', views.saveLiveSession),
    path('getSymetricKey', views.getSymetricKey),
    path('saveClientSession/', views.saveClientSession.as_view(), name='saveClientSession'),
    path('logData/', views.saveLogData.as_view(), name='logData'),
    path('getLogData/<int:providerId>/<str:machineName>', views.getLogData),
    path('clientState/', views.saveClientState.as_view(), name='clientState'),
    path('getClientState/<int:providerId>/<str:machineName>', views.getClientState),
    path('fileDetails/', views.saveFileDetails.as_view(), name='fileDetails'),
    path('getFileDetails/<int:providerId>/<str:machineName>', views.getFileDetails),
    path('uploadFile/<int:scheduleId>/<str:machineName>/<str:fileName>', views.postUploadFile),
    path('uploadFileStatus/', views.saveFileUpload.as_view(), name='uploadFileStatus'),
    path('providerStudents/<int:start>/<int:end>/<int:courseid>', views.getProviderStudents),
]

eLearningCMS/src/provider/urls.py
from django.urls import path
from . import views

app_name = 'provider'
urlpatterns = [
     path('', views.showProviderHome.as_view(), name="provider_home"),
     path('uploadVideo', views.uploadVideo.as_view(), name="upload_video"),
     path('createCourse', views.createCourse.as_view(), name="create_course"),
     path('editCourse/<int:id>', views.editCourse.as_view(), name="edit_course"),
     path('profile', views.ProviderProfile.as_view(), name="my_profile"),
     path('stats', views.myStats.as_view(), name="my_stats"),
     path('viewCourse', views.viewCourses.as_view(), name="view_courses"),
     path('viewVideo', views.viewSessions.as_view(), name="view_videos"),
     path('publishCourse', views.publishCourse.as_view(), name="publish_course"),
     path('createFromCourses', views.createFromCourses.as_view(), name="create_from_courses"),
     path('verifyEmail/<slug:slug>', views.VerifyEmail.as_view(), name="verify_email"),
     path('myStudents', views.myStudents.as_view(), name="my_students"),
     path('liveCapture', views.liveCapture.as_view(), name="live_capture"),
     path('addStudents/<slug:slug>', views.addStudents.as_view(), name="add_students"),
     path('getProviderProfile/<str:email>/<str:encpassword>', views.ProviderCourseDetails.as_view(), name="provider_profile"),
     path('deleteCourse/<int:id>', views.deleteCourse.as_view(), name="delete_course"),
     path('export_studentdata/<int:studentid>', views.export_users_csv, name='export_studentdata'),
     path('clear_enrollments/<int:id>', views.clear_enrollments.as_view(), name="clear_enrollments"),
     path('createMaterial', views.createMaterial.as_view(), name="create_material"),
     path('fix_expiry/<int:pid>/<int:nmonths>', views.fix_expiry, name='fix_expiry'),
     path('getProviderCDNDetails', views.getProviderCDNDetails, name='getProviderCDNDetails'),
     path('deleteMaterial/<int:cid>/<int:mid>/<int:chapid>/<int:sid>', views.deleteMaterial.as_view(), name="delete_material"),
     path('export_all_students_data', views.export_all_students_data, name='export_all_students_data'),
     path('delete_expired_students', views.delete_expired_students, name='delete_expired_students'),
     path('refresh_provider/<int:pid>/<int:secretkey>', views.refresh_provider, name='refresh_provider'),
]

eLearningCMS/src/schedule/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "schedule"

urlpatterns = [
     path("addShowSchedule", views.addShowSchedule.as_view(), name="add_show_schedule"),
     path("startCapture/<int:scheduleid>", views.startCapture.as_view(), name="startCapture"),
     path("stopCapture/<int:scheduleid>", views.stopCapture.as_view(), name="stopCapture"),
     path("systemName", views.addSystem.as_view(), name="systemName"),
     path("captureState/<int:scheduleid>", views.captureState.as_view(), name="captureState"),
     path("showLiveEvents", views.showLiveEvents.as_view(), name="showLiveEvents"),
     path('playStream/<int:scheduleid>', views.playStream.as_view(), name="playStream"),
     path('on_play', views.on_play.as_view(), name="on_play"),
     path('on_publish', views.on_publish.as_view(), name="on_publish"),
     path('on_publish_done', views.on_publish_done.as_view(), name="on_publish_done"),
     path('deleteSchedule/<int:scheduleid>', views.deleteSchedule.as_view(), name="deleteSchedule"),
]

eLearningCMS/src/schedule/models.py
from django.db import models
import provider
import course
import student

# Create your models here.

class Schedule(models.Model):
    provider = models.ForeignKey(provider.models.Provider, on_delete=models.CASCADE)
    chapter = models.ForeignKey(course.models.CourseChapter, on_delete=models.CASCADE)
    start = models.DateTimeField(auto_now_add=True)
    eventcount = models.IntegerField(default=1) #number
    duration = models.IntegerField(default=60) #minutes
    recurafter = models.IntegerField(default=0) #0 hours => does not recur
    autopublish = models.BooleanField(default=False)
    running = models.IntegerField(default=0)
    system = models.CharField(default='', max_length=100)
    streamkey = models.CharField(default='',max_length=256)
    streamname = models.CharField(default='',max_length=256)
    encrypted = models.BooleanField(default=False)

class Schedule_liveaccess(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    student = models.ForeignKey(student.models.Student, on_delete=models.CASCADE)
    ip = models.CharField(default='', max_length=100)
    nginxip = models.CharField(default='', max_length=100)

eLearningCMS/src/schedule/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.conf import settings
import course
from course import models
from provider.views import showProviderHome, getProvider
from django.forms.models import model_to_dict
from django.http import HttpResponse
from django.http import Http404
from Crypto.Cipher import AES
from . import models
import provider
import schedule
import pusher
import pysher
import websocket
import enum
import json
import base64
import student
import cdn
from django.db.models import Q
from django.urls import reverse
from access.views import parse_user_agents
from urllib.parse import urlencode

PUSHER_APP_ID = "656749"
PUSHER_KEY = "3ff394e3371be28d8abd"
PUSHER_SECRET = "35f5a7cde33cd756c30d"
PUSHER_CLUSTER = "ap2"


# Commands
command_start = 0
command_stop = 1

# Status
status_start_success = 0
status_capture_started = 1
status_no_capture_started = 2
status_camera_not_detected = 3
status_stop_success = 4

# schedule states
STOPPED = 0
RUNNING = 1
UPLOADING = 2

# Macros for Storage locations
DO = 1
BUNNY = 2

class HttpResponseNoContent(HttpResponse):
    status_code = 200

# Create your views here.
# Authenticate that provider has rights to publish live streaming
class on_publish(generic.TemplateView):
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        #return HttpResponse(status=404)

        scheduleid = request.GET.get('scheduleid', '')
        providerid = request.GET.get('providerid', '')
        #sessionKey = request.GET.get('sessionKey', '')
        if scheduleid == '' or providerid == '':
            return HttpResponse(status=404)
        scheduleObj = models.Schedule.objects.filter(id=scheduleid,provider_id=providerid)
        if not scheduleObj:
            return HttpResponse(status=404)
        scheduleObj = scheduleObj[0]
        # clear stream_access table for this schedule id
        schedule_liveaccessObj = models.Schedule_liveaccess.objects.filter(schedule_id=scheduleObj.id)
        if schedule_liveaccessObj:
            schedule_liveaccessObj.delete()
        return HttpResponse(status=201)

# Authenticate live streaming view by user
class on_play(generic.TemplateView):
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        #return HttpResponse(status=201)
        # this is client ip received from nginx
        ipaddr = request.GET.get('addr', '')
        scheduleid = request.GET.get('scheduleid', '')
        providerid = request.GET.get('providerid', '')
        studentid = request.GET.get('studentid', '')
        userIP = request.GET.get('userIP', '')
        
        if scheduleid == '' and studentid == '' and providerid == '':
            scheduleObj = models.Schedule.objects.filter(streamkey=ipaddr)
            if scheduleObj:
                return HttpResponse(status=201)
            schedule_liveaccessObj = models.Schedule_liveaccess.objects.filter(nginxip=ipaddr)
            if schedule_liveaccessObj:
                return HttpResponse(status=201)
        elif studentid != '' and scheduleid != '' and userIP != '':
            schedule_liveaccessObj = models.Schedule_liveaccess.objects.filter(schedule_id=scheduleid,student_id=studentid)
            if not schedule_liveaccessObj:
                return HttpResponse(status=404)
            schedule_liveaccessObj = schedule_liveaccessObj[0]
            if schedule_liveaccessObj.nginxip == ipaddr and schedule_liveaccessObj.ip == userIP:
                return HttpResponse(status=201)
            if schedule_liveaccessObj.nginxip == '':
                schedule_liveaccessObj.nginxip = ipaddr
                schedule_liveaccessObj.save()
                return HttpResponse(status=201)
        elif providerid != '' and scheduleid != '' and userIP != '':
            scheduleObj = models.Schedule.objects.filter(id=scheduleid,provider_id=providerid)
            if not scheduleObj:
                return HttpResponse(status=404)
            scheduleObj = scheduleObj[0]
            if scheduleObj.streamkey == ipaddr:
                return HttpResponse(status=201)
            if scheduleObj.streamkey == '':
                scheduleObj.streamkey = ipaddr
                scheduleObj.save()
                return HttpResponse(status=201)
        return HttpResponse(status=404)

# Authenticate live streaming view by user
class on_publish_done(generic.TemplateView):
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        return HttpResponse(status=201)

def getActiveSchedules(providerId):
    scheduleObj = models.Schedule.objects.filter(provider_id=providerId)
    activeCount = 0
    for schedule in scheduleObj:
        chapterObj = course.models.CourseChapter.objects.filter(id=schedule.chapter_id)[0]
        sessions = chapterObj.sessions
        sessionsCount = 0
        if sessions != '':
            sessionsCount = len(sessions.split(','))
        if sessionsCount < schedule.eventcount:
            activeCount = activeCount+1
    return activeCount

def isAnyEventLive(request):
    scheduleObj = models.Schedule.objects.filter(running=1)
    if not scheduleObj:
        return False
    if request.user.is_staff:
        # Get Live events of Scheduled courses
        providerObj = getProvider(request)
        scheduleObj = scheduleObj.filter(provider_id=providerObj.id)
    else:
        # Get live events of enrolled courses
        scheduleObj = scheduleObj.filter(autopublish=True)
        studentObj = student.models.Student.objects.filter(user_id=request.user.id)[0]
        courseIds = course.algos.getEnrolledCourseIds(request)
        enrolledCourseObj = course.models.EnrolledCourse.objects.filter(student_id=studentObj.id,active=True,course_id__in=courseIds)
        chaptersList = []
        for ec in enrolledCourseObj:
            if ec.chapteraccess == '':
                courseChapterObj = course.models.CourseChapter.objects.filter(course_id=ec.course_id)
                for cco in courseChapterObj:
                    chaptersList.append(cco.id)
            else:
                allowedModules = ec.chapteraccess.split(',')
                allowedModulesInt = [int(i) for i in allowedModules]
                chaptersList.extend(allowedModulesInt)
            #courseChapterObj = course.models.CourseChapter.objects.filter(Q(course_id__in=enrolledCourseObj.values('course_id'))).values('id')
        scheduleObj = scheduleObj.filter(Q(chapter_id__in=chaptersList))

    if scheduleObj :
        return True
    return False

class showLiveEvents(provider.views.showProviderHome,LoginRequiredMixin,generic.TemplateView):
    template_name = "showLiveEvents.html"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        
        scheduleObj = models.Schedule.objects.filter(running=1)
        kwargs["disableKeys"] = "true"
        if not scheduleObj:
            return super().get(request, *args, **kwargs)
        if request.user.is_staff:
            # Get Live events of Scheduled courses
            providerObj = getProvider(request)
            scheduleObj = scheduleObj.filter(provider_id=providerObj.id)
        else:
            # Get live events of enrolled courses
            scheduleObj = scheduleObj.filter(autopublish=True)
            studentObj = student.models.Student.objects.filter(user_id=request.user.id)[0]
            courseIds = course.algos.getEnrolledCourseIds(request)
            enrolledCourseObj = course.models.EnrolledCourse.objects.filter(student_id=studentObj.id,active=True,course_id__in=courseIds)
            chaptersList = []
            for ec in enrolledCourseObj:
                if ec.chapteraccess == '':
                    courseChapterObj = course.models.CourseChapter.objects.filter(course_id=ec.course_id)
                    for cco in courseChapterObj:
                        chaptersList.append(cco.id)
                else:
                    allowedModules = ec.chapteraccess.split(',')
                    allowedModulesInt = [int(i) for i in allowedModules]
                    chaptersList.extend(allowedModulesInt)
            #courseChapterObj = course.models.CourseChapter.objects.filter(Q(course_id__in=enrolledCourseObj.values('course_id'))).values('id')
            scheduleObj = scheduleObj.filter(Q(chapter_id__in=chaptersList))

        if scheduleObj :
            schedules = []
            kwargs["live"] = 'on'
            for schedule in scheduleObj:
                scheduleInfo = model_to_dict(schedule)
                chapterObj = course.models.CourseChapter.objects.filter(id=schedule.chapter_id)[0]
                sessions = chapterObj.sessions
                sessionsCount = 0
                if sessions != '':
                    sessionsCount = len(sessions.split(','))

                scheduleInfo['id'] = schedule.id
                scheduleInfo['chapterName'] = chapterObj.name
                scheduleInfo['subjectName'] = chapterObj.subject
                scheduleInfo['courseName'] = course.models.Course.objects.filter(id=chapterObj.course_id)[0].name
                scheduleInfo['courseId'] = chapterObj.course_id
                schedules.append(scheduleInfo)
            kwargs['schedules'] = schedules
        return super().get(request, *args, **kwargs)

class addShowSchedule(showProviderHome):
    template_name = "addShowSchedule.html"
    http_method_names = ['get','post']

    def get(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise Http404()

        providerObj = getProvider(request)
        kwargs["disableKeys"] = "false"
        locations = []
        locationObj = provider.models.System.objects.filter(provider_id=providerObj.id)
        for location in locationObj:
            locations.append(location.name)
        kwargs['locations'] = locations

eLearningCMS/src/schedule/templates/addShowSchedule.html
{% extends "__user_base.html" %}
{% load staticfiles %}

{% block active %}
  <!-- Breadcrumbs-->
  <nav class="navbar">
  <div class="mr-lg-auto">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Event Scheduler</li>
  </ol>
  </div>
  <a href="" data-toggle="modal" data-target="#scheduleModal" class="btn btn-outline-info btn-lg mx-2 px-2" role="button" aria-pressed="true">Create</a>

  
  </nav>


  <div id="scheduleModal" class="modal" role="dialog">
		<div class="modal-dialog">
	  <!-- Modal content-->
	  <div class="modal-content">
	  <div class="modal-header">
	  <h4 class="modal-title">Create/Edit Schedule</h4>
	  <button type="button" class="close" data-dismiss="modal">×</button>
	  </div>
	  <div class="modal-body">
      <form  method="post" enctype="multipart/form-data"> {% csrf_token %}
        <div class="form-group row">
          <label for="courseName" class="col-sm-4 col-form-label">Course</label>
          <div class="col-sm-8">
            <select name="courseName" class="form-control" id="courseName" data-live-search="true" onchange="fillSelectByName(this,'courseSubjectName','courseChapterName')" >
                {% for course in mycourses %}
              <option value="{{ course.name }}" >{{ course.name }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="form-group row">
          <label for="courseSubjectName" class="col-sm-4 col-form-label">Subject</label>
          <div class="col-sm-8">
            <select id="courseSubjectName" name="courseSubjectName" class="form-control" data-live-search="true" onchange="fillSelectByName(this,'courseChapterName')">
                {% for course in mycourses %}
                  {% for sub, subDetails in course.details.items %}
              <option value="{{ course.name }}:{{sub}}" >{{sub}}</option>
                  {% endfor %}
                {% endfor %}
            </select>
          </div>
        </div>
        <div class="form-group row">
          <label for="courseChapterName" class="col-sm-4 col-form-label">Chapter</label>
          <div class="col-sm-8">
            <select id="courseChapterName" name="courseChapterName" class="form-control" data-live-search="true">
                {% for course in mycourses %}
                  {% for sub, subDetails in course.details.items %}
                    {% for subject in subDetails %}
                     {% for chapId, chapDetails in subject.items %}
                       <option value="{{ course.name }}:{{sub}}:{{chapId}}" >{{ chapDetails.name }}</option>
                     {% endfor %}
                    {% endfor %}
                  {% endfor %}
                {% endfor %}
            </select>
            <input type="hidden" id="scheduleChapterId" name="scheduleChapterId" value="" />
          </div>
        </div>
        {% if locations|length < 2 %}
        <div class="form-group row" style="display:none;" >
          {% else %}
          <div class="form-group row">
          {% endif %}
          <label for="courseLocation" class="col-sm-4 col-form-label">Location</label>
          <div class="col-sm-8">
            <select id="courseLocation" name="courseLocation" class="form-control" data-live-search="true">
                {% for location in locations %}
                       <option value="{{location}}" >{{ location }}</option>
                {% endfor %}
            </select>
          </div>
        </div>
        <div class="form-group row" style="display:none;">
          <label for="startDate" class="col-sm-4 col-form-label">Starts On</label>
          <div class="col-sm-8">
            <input type="date" class="form-control" name="startDate" id="startDate" placeholder="Start Date" >
          </div>
        </div>
        <div class="form-group row" style="display:none;">
          <label for="eventTime" class="col-sm-4 col-form-label">Time</label>
          <div class="col-sm-8">
            <input type="time" class="form-control" name="eventTime" id="eventTime" value="00:00" placeholder="Start Time" >
          </div>
        </div>
		<div class="form-group row">
          <label for="eventDuration" class="col-sm-4 col-form-label">Duration (mins)</label>
          <div class="col-sm-8">
            <input type="number" class="form-control" name="eventDuration" id="eventDuration" value=120 placeholder="Event Duration in minutes" required>
          </div>
        </div>
        <div class="form-group row">
          <label for="eventCount" class="col-sm-4 col-form-label">Total Sessions</label>
          <div class="col-sm-8">
            <input type="number" class="form-control" name="eventCount" id="eventCount" value=10 placeholder="Number of Sessions for this chapter" required>
          </div>
        </div>
        <div class="form-group row" style="display:none;">
          <label for="eventRecur" class="col-sm-4 col-form-label">Repeats Every (hours)</label>
          <div class="col-sm-8">
            <input type="number" class="form-control" name="eventRecur" id="eventRecur" value=24 placeholder="Repeats every in hours" required>
          </div>
        </div>
        <div class="form-group row">
          <label for="autoPublish" class="col-sm-4 col-form-label">Publish Session</label>
          <div class="col-sm-8">
            <input type="checkbox" class="form-control" name="autoPublish" id="autoPublish">
          </div>
        </div>
	    <!--div class="form-group row">
          <label for="encrypt" class="col-sm-4 col-form-label">Encrypt Session</label>
          <div class="col-sm-8">
            <input type="checkbox" class="form-control" name="encrypt" id="encrypt">
          </div>
        </div-->
        <div class="form-group row">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </div>
      </form>
	  </div>
	  
	  </div>
	  
	   </div>
	  </div>

    <div class="container-fluid">
        {% if schedules|length > 0 %}
        <h5>Scheduled Course Events</h5>
        <div style="overflow-x:auto;">
        <table class="table" id="schedulesTable">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Course</th>
                <th scope="col">Subject</th>
                <th scope="col">Chapter</th>
                {% if locations|length > 1 %}
                 <th scope="col">Location</th>
                 {% else %}
                 <th scope="col" style="display:none;">Location</th> 
                 {% endif %}
                <th scope="col" style="display:none;">Starts From</th>
                <th scope="col">Duration</th>
                <th scope="col">Total Sessions</th>
                <th scope="col">Sessions Finished</th>
                <th scope="col">Publish</th>
                <!--th scope="col">Encrypt</th-->
              </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row"></th>
                    <td><input type="text" id="filterCourse" onkeyup="filterFunction('filterCourse','schedulesTable')" placeholder="Filter Course.."></td>
                    <td><input type="text" id="filterSubject" onkeyup="filterFunction('filterSubject','schedulesTable')" placeholder="Filter Subject.."></td>
                    <td><input type="text" id="filterChapter" onkeyup="filterFunction('filterChapter','schedulesTable')" placeholder="Filter Chapters.."></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    
                  </tr>
            {% for schedule in schedules %}
              <tr>
                <th scope="row">
                  <a href="{% url 'schedule:deleteSchedule' schedule.id %}" class="btn btn-primary btn-sm mx-2 px-2" role="button" aria-pressed="true" onclick="return confirm('Do you want to delete this schedule?')">
                    <i class="fa fa-trash fa-sm" title="Delete Schedule"></i></a>
                </th>
                <td><a href="{% url 'provider:edit_course' schedule.courseId %}"> {{schedule.courseName}} </a></td>
                <td>{{schedule.subjectName}}</td>
                <td >{{schedule.chapterName}}</td>
                {% if locations|length > 1 %}
                <td>{{schedule.system}}</td>
                {% else %}
                <td style="display:none;">{{schedule.system}}</td>
                {% endif %}
                <td style="display:none;">{{schedule.start}}</td>
                <td>{{schedule.duration}}</td>
                <td>{{schedule.eventcount}}</td>
                <td>{{schedule.eventsOccured}}</td>
                <td>{{schedule.autoPublish}}</td>
                <!--td>{{schedule.encrypted}}</td-->
                <td><button class="btn btn-info btn-sm mx-2 px-2" aria-pressed="true" onclick="editSchedule(this)"><i class="fa fa-edit fa-sm" title="Edit schedule"></i></td>
                {% if schedule.eventsRemaining != 0 %}
                  {% if schedule.running == 0 %}
                  <td><a href="{% url 'schedule:startCapture' schedule.id %}" class="btn btn-dark btn-sm mx-2 px-2" role="button" aria-pressed="true"><i class="fa fa-circle fa-sm" title="Start capture"></i></a></td>              
                  {% elif  schedule.running == 1 %}
                  <td><i class="fas fa-sync fa-spin" title="Capturing"></i></td>
                  <td><a href="{% url 'schedule:stopCapture' schedule.id %}" class="btn btn-danger btn-sm mx-2 px-2" role="button" aria-pressed="true"><i class="fa fa-circle fa-sm" title="Stop capture"></i></a></td>
                  {% else %}
                  <td><i class="fas fa-spinner fa-pulse"></i> uploading...</td> 
                  {% endif %}
                {% else %}
                <td><font color="red"> Completed </font></td>
                {% endif %}
                <!--<td><a href="" class="btn btn-info btn-sm mx-2 px-2" role="button" aria-pressed="true">Mark Completed</a></td> -->
              </tr>
              {% endfor %}    
            </tbody>
          </table>
          </div>
        
        {% else %}
        <h5>No Schedule Planned</h5>
        {% endif %}
    </div>
  <script src="{% static 'provider/js/createCourseContent.js' %}">
  </script>
<script>
    var doRefresh = "{{doRefresh}}";
    window.onload = function() {
      setTimeout(function () {
        if(window.location.hash != '#refresh' && doRefresh == "1") {
          window.location.hash = 'refresh';
          window.location.reload(1);
        }
      }, 3000);  // After 5 secs
    }
    var selectElement = document.getElementById('courseName');
    fillSelectByName(selectElement,'courseSubjectName','courseChapterName');
</script>
{% endblock active %}

eLearningCMS/src/schedule/templates/playSchedule.html
{% include "playSessionLive.html" %}

eLearningCMS/src/schedule/templates/showLiveEvents.html
{% extends "__user_base.html" %}
{% load staticfiles %}

{% block active %}
  <!-- Breadcrumbs-->
  <nav class="navbar">
  <div class="mr-lg-auto">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Event Scheduler</li>
  </ol>
  </div>
    
  </nav>


   <div class="container-fluid">
        {% if schedules|length > 0 %}
        <h5>Live Events Running</h5>
        <div style="overflow-x:auto;">
        <table class="table" id="liveEventsTable">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Course</th>
                <th scope="col">Subject</th>
                <th scope="col">Chapter</th>
              </tr>
            </thead>
            <tbody>
            {% for schedule in schedules %}
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td> {{schedule.courseName}} </td>
                <td>{{schedule.subjectName}}</td>
                <td >{{schedule.chapterName}}</td>
                <td><a href="{% url 'schedule:playStream' schedule.id %}" class="btn btn-dark btn-sm mx-2 px-2" role="button" aria-pressed="true"><i class="fa fa-play fa-sm" title="Play"></i></a></td>
              </tr>
              {% endfor %}    
            </tbody>
          </table>
          </div>
        
        {% else %}
        <h5>No Live Event</h5>
        {% endif %}
    </div>
{% endblock active %}