eLearningCMS/src/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('registerprovider/', views.RegisterProviderView.as_view(), name='registerprovider'),
    path('password-change/', views.PasswordChangeView.as_view(),
         name='password-change'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password-reset'),
    path('password-reset/done/', views.PasswordResetDoneView.as_view(), name='password-reset-done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
]

eLearningCMS/src/cdn/urls.py
from django.urls import path
from . import views
from rest_framework.schemas import get_schema_view # new

schema_view = get_schema_view(title='Pastebin API') # new

app_name = 'cdn'
urlpatterns = [
    path('schema/', schema_view), # new
    path('getUploadPaths/<int:count>', views.getUploadPaths),
    path('saveLiveSession/<str:videoKey>/<int:chapterId>', views.saveLiveSession),
    path('getSymetricKey', views.getSymetricKey),
    path('saveClientSession/', views.saveClientSession.as_view(), name='saveClientSession'),
    path('logData/', views.saveLogData.as_view(), name='logData'),
    path('getLogData/<int:providerId>/<str:machineName>', views.getLogData),
    path('clientState/', views.saveClientState.as_view(), name='clientState'),
    path('getClientState/<int:providerId>/<str:machineName>', views.getClientState),
    path('fileDetails/', views.saveFileDetails.as_view(), name='fileDetails'),
    path('getFileDetails/<int:providerId>/<str:machineName>', views.getFileDetails),
    path('uploadFile/<int:scheduleId>/<str:machineName>/<str:fileName>', views.postUploadFile),
    path('uploadFileStatus/', views.saveFileUpload.as_view(), name='uploadFileStatus'),
    path('providerStudents/<int:start>/<int:end>/<int:courseid>', views.getProviderStudents),
]

eLearningCMS/src/course/urls.py
from django.urls import path
from . import views
from rest_framework.schemas import get_schema_view # new

schema_view = get_schema_view(title='Pastebin API') # new

app_name = 'course'
urlpatterns = [
     path('coursePage/<int:id>', views.courseDetails.as_view(), name="coursePage"),
     path('addReview/<int:id>', views.addReview.as_view(), name="addReview"),
     path('playSession/<int:chapterid>/<int:sessionid>', views.playSession.as_view(), name="playSession"),
     path('playSessionEnc/<int:chapterid>/<int:sessionid>', views.playSessionEnc.as_view(), name="playSessionEnc"),
     path('updateDurationPlayed/<int:enrolledcourseid>/<int:duration>/<int:live>', views.updateDuration),
     path('updateDurationPlayedProvider/<int:courseid>/<int:duration>', views.updateDurationProvider),
]

eLearningCMS/src/provider/urls.py
from django.urls import path
from . import views

app_name = 'provider'
urlpatterns = [
     path('', views.showProviderHome.as_view(), name="provider_home"),
     path('uploadVideo', views.uploadVideo.as_view(), name="upload_video"),
     path('createCourse', views.createCourse.as_view(), name="create_course"),
     path('editCourse/<int:id>', views.editCourse.as_view(), name="edit_course"),
     path('profile', views.ProviderProfile.as_view(), name="my_profile"),
     path('stats', views.myStats.as_view(), name="my_stats"),
     path('viewCourse', views.viewCourses.as_view(), name="view_courses"),
     path('viewVideo', views.viewSessions.as_view(), name="view_videos"),
     path('publishCourse', views.publishCourse.as_view(), name="publish_course"),
     path('createFromCourses', views.createFromCourses.as_view(), name="create_from_courses"),
     path('verifyEmail/<slug:slug>', views.VerifyEmail.as_view(), name="verify_email"),
     path('myStudents', views.myStudents.as_view(), name="my_students"),
     path('liveCapture', views.liveCapture.as_view(), name="live_capture"),
     path('addStudents/<slug:slug>', views.addStudents.as_view(), name="add_students"),
     path('getProviderProfile/<str:email>/<str:encpassword>', views.ProviderCourseDetails.as_view(), name="provider_profile"),
     path('deleteCourse/<int:id>', views.deleteCourse.as_view(), name="delete_course"),
     path('export_studentdata/<int:studentid>', views.export_users_csv, name='export_studentdata'),
     path('clear_enrollments/<int:id>', views.clear_enrollments.as_view(), name="clear_enrollments"),
     path('createMaterial', views.createMaterial.as_view(), name="create_material"),
     path('fix_expiry/<int:pid>/<int:nmonths>', views.fix_expiry, name='fix_expiry'),
     path('getProviderCDNDetails', views.getProviderCDNDetails, name='getProviderCDNDetails'),
     path('deleteMaterial/<int:cid>/<int:mid>/<int:chapid>/<int:sid>', views.deleteMaterial.as_view(), name="delete_material"),
     path('export_all_students_data', views.export_all_students_data, name='export_all_students_data'),
     path('delete_expired_students', views.delete_expired_students, name='delete_expired_students'),
     path('refresh_provider/<int:pid>/<int:secretkey>', views.refresh_provider, name='refresh_provider'),
]

eLearningCMS/src/provider/forms.py
from __future__ import unicode_literals
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from . import models
import course

class uploadVideoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.layout = Layout(
            Field('name', placeholder='Enter lecture name'),
            Submit('update', 'Update', css_class="btn-success"),
        )

    class Meta:
        model = models.Session
        fields = ['name', 'video']

class uploadFilesForm(forms.ModelForm):
    class Meta:
        model = models.Session
        fields = ['video',]

class courseCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.layout = Layout(
            Field('name', placeholder='Enter Course name'),
            Field('exam', placeholder='Enter Exam'),
            Field('cost'),
            Field('duration', placeholder='Enter Course duration in months'),
            Field('published'),
            Submit('update', 'Update', css_class="btn-success"),
        )

    class Meta:
        model = course.models.Course
        fields = ['name', 'exam', 'cost', 'duration', 'published']

eLearningCMS/src/provider/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.views.generic.edit import CreateView
from django.shortcuts import redirect
from . import models
from django.http import JsonResponse
from django.db.models import Q
from django.http import Http404
from . import forms
import course
import datetime
import profiles
import json
from django.forms.models import model_to_dict
from django.conf import settings
import notification
import student
import os
from examcracker import thread
import cdn
import schedule
from django.contrib.auth import get_user_model
from Crypto.Cipher import AES
from django.contrib.auth import authenticate
import base64
import string
import random
import csv
from django.http import HttpResponse
from datetime import date,datetime
from dateutil.relativedelta import relativedelta
# Rest based modules
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
import xlsxwriter
import calendar

def pwd_generator(size=6, chars=string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

def getDelimiter(subject=False):
    if not subject:
        return course.algos.DELIMITER
    else :
        return course.algos.SUBJECTS_DELIMITER

def getProvider(request):
    providerObj = models.Provider.objects.filter(user_id=request.user.id)
    if providerObj.exists():
      return providerObj[0]
    else:
      return providerObj

def getSessionsBySubjects(providerId,subjects):
    subjectarr = subjects.split(getDelimiter(True))
    sessionObj = models.Session.objects.filter(provider_id=providerId)
    q_objects = Q()
    for sub in subjectarr:
        q_objects.add(Q(tags__icontains=sub), Q.OR)
    sessionObj = sessionObj.filter(q_objects)
    return sessionObj

def getTotalStudentsPlayedTime(providerId,onlyLive=False):
    providerCourses = course.models.Course.objects.filter(provider_id=providerId)
    myec = course.models.EnrolledCourse.objects.filter(course_id__in=providerCourses.values('id'))
    viewHours = 0
    for ec in myec:
        if onlyLive == True:
            viewHours = viewHours + ec.completedminuteslive
        else:
            viewHours = viewHours + ec.completedminutes + ec.completedminuteslive
    return (int(viewHours))


def getProviderStats(providerId):
    coursesObj = course.models.Course.objects.filter(Q(provider_id=providerId) & Q(published=1))
    sessionObj = models.Session.objects.filter(provider_id=providerId)
    providerStatsInfo = {}
    courses = []
    courses.append(['Courses', 'Students per course'])
    providerStatsInfo['totalCourses'] = '{:,}'.format(len(coursesObj))
    providerStatsInfo['totalSessions'] = '{:,}'.format(len(sessionObj))
    totalStudents = 0
    totalRevenue = 0
    totalViewedMinutes = 0
    for courseObj in coursesObj:
        courseStat = []
        courseStat.append(courseObj.name)
        studentsPerCourse = len(course.models.EnrolledCourse.objects.filter(course_id=courseObj.id))
        totalStudents += studentsPerCourse
        totalRevenue += int(studentsPerCourse*courseObj.cost)
        totalViewedMinutes += int(courseObj.completedseconds/60)
        courseStat.append(studentsPerCourse)
        courses.append(courseStat)
    
    providerStatsInfo['totalStudents'] = '{:,}'.format(totalStudents)
    providerStatsInfo['totalRevenue'] = '{:,}'.format(totalRevenue)
    providerStatsInfo['activeSchedules'] = schedule.views.getActiveSchedules(providerId)
    providerStatsInfo['piechartArray'] = courses
    providerStatsInfo['completedtime'] = str(int(totalViewedMinutes/60)) + " : " + str(int(totalViewedMinutes%60))
    viewMinutesByStudents = getTotalStudentsPlayedTime(providerId)
    planObj = models.Plan.objects.filter(provider_id=providerId)
    if planObj:
        planObj = planObj[0]
        viewMinutesByStudents = viewMinutesByStudents + planObj.completedminutes + planObj.completedminuteslive
    providerStatsInfo['totalStudentsPlayedTime'] = int (viewMinutesByStudents/60)
    return providerStatsInfo

class showProviderHome(LoginRequiredMixin, generic.TemplateView):
    template_name = 'provider_home.html'
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        notifications = (notification.models.UserNotification.objects.filter(user=request.user.id))
        unseenNotifications = len(notifications.filter(saw=0))
        # set total count of notifications
        kwargs["notificationsCount"] = unseenNotifications
        notifications = notifications.filter(saw=False)
        kwargs["notifications"] = reversed(notifications)
        kwargs["disableKeys"] = "false"
        providerObj = getProvider(request)
        if not providerObj :
            return super().get(request, *args, **kwargs)
        if settings.PROVIDER_APPROVAL_NEEDED and not providerObj.approved:
            kwargs["not_approved"] = True
        else:
            kwargs["statsInfo"] = getProviderStats(providerObj.id)
         
        if schedule.views.isAnyEventLive(request):
            kwargs["live"] = 'on'
        else:
            kwargs["live"] = 'off'

        return super().get(request, *args, **kwargs)

class uploadVideo(LoginRequiredMixin, generic.TemplateView):
    template_name = "create_course.html"
    http_method_names = ['post']
    
    def post(self, request):
        providerObj = getProvider(request)
        videoForm = forms.uploadFilesForm(self.request.POST,self.request.FILES)
        courseid = self.request.POST.get('coid','')
        subject = ''

        if courseid != "":
            courseObj = course.models.Course.objects.filter(id=int(courseid))[0]
            subject = courseObj.subjects
        if videoForm.is_valid():
            sessionObj = videoForm.save(commit=False)
            sessionObj.provider = getProvider(request)
            sessionObj.name = sessionObj.video.name
            if subject != '':
                sessionObj.tags = subject
            sessionObj.save()
            videoForm.save()
            data = {'is_valid': True, 'videoId': sessionObj.id, 'videoName': sessionObj.name}
            return JsonResponse(data)
        else:
            data = {'is_valid': False}
            return JsonResponse(data)

class SessionDurationFetch(thread.CallBackObject):
    def __init__(self, sessionObj):
        super().__init__()
        self.sessionObj = sessionObj

    def execute(self):
        self.sessionObj.duration = cdn.views.getVideoDuration(self.sessionObj.videoKey)

    def terminate(self):
        if self.sessionObj.duration is None:
            return False
        if self.sessionObj.duration == 0:
            return False
        self.sessionObj.ready = True
        self.sessionObj.save()
        return True

def saveCourseContent(request,courseId):
    if 'lcids' not in request.POST:
        return
    courseObj = course.models.Course.objects.filter(id=courseId)[0]
    lcids = request.POST.getlist('lcids')
    chapterNameList = request.POST.getlist('cd[]')
    if len(lcids) > 0:
        i = 0
        subjectChapterCntMap = {}
        chpArr = []
        chpNameIndex = 0
        while i < len(lcids):
            cpid = lcids[i].split('-')
            subject = cpid[1]
            cpSuffix = 1
            chapterName = chapterNameList[chpNameIndex]
            chpNameIndex = chpNameIndex + 1
            if subject not in subjectChapterCntMap:
                subjectChapterCntMap[subject] = 1
                cpSuffix = 1
            else:
                subjectChapterCntMap[subject] = subjectChapterCntMap[subject] + 1
                cpSuffix = subjectChapterCntMap[subject]
            chapterObj = course.models.CourseChapter.objects.filter(id=cpid[0],course_id=courseId,subject=subject)
            if chapterObj.exists():
                chapterObj = chapterObj[0]
            else:
                chapterObj = course.models.CourseChapter()
                chapterObj.course = courseObj
                #chapterObj.name = cpPrefix +' ' +str(cpSuffix) + ': ' + chapterName
            chapterObj.name = chapterName
            #chapterObj.name = cpPrefix +' ' +str(cpSuffix)
            chapterObj.sequence = i+1
            chapterObj.subject = subject

            # first get and save files into provider_session db
            sessionsIdArr = []
            publishedArr = []
            # get session ids here
            lcVar = 'lec['+str(cpid[0])+'][]'
            lecPubVar = 'lecPub['+str(cpid[0])+'][]'
            if lcVar in request.POST:
                filesUploaded = request.POST.getlist(lcVar)
                filePublishedArr = request.POST.getlist(lecPubVar)
                j=0
                while j < len(filesUploaded):
                    sessionId = filesUploaded[j]

                    try:
                        filesUploaded[j] = int(filesUploaded[j])
                    except:
                        sessionObj = models.Session()
                        sessionObj.provider = getProvider(request)
                        argumentList = sessionId.split('?')
                        sessionObj.videoKey = argumentList[0]
                        sessionObj.name = os.path.splitext(argumentList[1])[0]
                        sessionObj.tags = chapterObj.subject
                        sessionObj.save()
                        sessionId = str(sessionObj.id)

                    sname = request.POST.get('sname['+str(sessionId)+']','')               
                    if sname != '':
                        sessionObj = models.Session.objects.filter(id=sessionId)
                        sessionObj = sessionObj[0]
                        sessionObj.name = sname
                        sessionObj.save()
                    sessionsIdArr.append(sessionId)

eLearningCMS/src/provider/templates/course_detail.html
{% extends "__user_base.html" %}
{% load staticfiles %}
{% block active %}
<div class="panel-body">
	<strong>Name</strong>: {{ course_detail.name }}<br>
	<strong>Created On</strong>: {{ course_detail.created }}<br>
	<strong>Exam</strong>: {{ course_detail.exam }}<br>
	<strong>Cost (INR)</strong>: {{ course_detail.cost }}<br>
	<strong>Duration (months)</strong>: {{ course_detail.duration }}<br>
</div>
<div class="panel-body">
	<strong>Course Sessions</strong><br>
	{% if included_sessions %}
	<ol>
	{% for session in included_sessions %}
		<label for="video"><a href="{% url 'provider:video_detail' session.id %}">{{ session.name }}</a></label><br>
	{% endfor %}
    </ol>
	{% endif %}
</div>
<div>
	<strong>Sessions Not In course</strong><br>
	<form action="" method="post" enctype="multipart/form-data">
	{% if excluded_sessions %}
		<ol>
		{% for session in excluded_sessions %}
		<input type="checkbox" name="sessions[]" value="{{ session.id }}"</input>
		<label for="video"><a href="{% url 'provider:video_detail' session.id %}">{{ session.name }}</a></label><br>
		{% endfor %}
    	</ol>
		{% endif %}
		{% csrf_token %}
		<div class="form-group">
	  		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Add</button>
			</div>
			{% if course_detail.published %}
			{% else %}
				<div class="col-sm-offset-2 col-sm-10">
	  			<button type="submit" class="btn btn-success">Publish</button>
				</div>
			{% endif %}
 		 </div>
	</form>
</div>  
{% endblock active %}

eLearningCMS/src/provider/templates/create_course.html
{% extends "__user_base.html" %}
{% load staticfiles %}
{% block active %}
{% load thumbnail %}

<nav id="courseNavBar" class="navbar">
<div class="mr-lg-auto">
<ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="#">Dashboard</a>
    </li>
	<li class="breadcrumb-item active">
			{% if editCourse %}
			Edit Course / {{ editCourse.name }}
			{%  else %}
			Create New Course 
		{% endif %}
	</li>

	<!--<button class="btn btn-sm btn-success float-right" style="position:absolute;right:10rem;">Preview Course</button>-->
</ol>
</div>
{% if editCourse %}
<form class="form-inline" action="{% url 'provider:clear_enrollments' editCourse.id %}" id="clear_enrollments"  method="post" enctype="multipart/form-data"> {% csrf_token %}
	<button class="btn btn-outline-danger btn-lg float-right" type="button" id="clear_enrollmentsButton" title = "Deletes all students enrollments of this course"
	onclick="clear_enrollments(this)" {% if not editCourse %} disabled {% endif %} >Clear Enrollments</button>
</form>

<form class="form-inline" action="{% url 'provider:delete_course' editCourse.id %}" id="deleteMyCourse"  method="post" enctype="multipart/form-data"> {% csrf_token %}
	<button class="btn btn-outline-dark btn-lg float-right" type="button" id="deleteCourseButton" title = "Delete this course"
	onclick="deleteMyCourse(this)" {% if not editCourse %} disabled {% endif %} >Delete</button>
</form>

<a href="{% url 'course:coursePage' editCourse.id %}" id="previewCourseButton" class="btn btn-outline-secondary btn-lg mx-2 px-2" role="button" aria-pressed="true">Preview</a>

{% if not editContentDisable %}
<button class="btn btn-outline-info btn-lg mx-2 px-2" id="saveCourseButton" aria-pressed="true" onclick="saveCourse(this)">Save</button>
{% endif %}
<form class="form-inline" action="{% url 'provider:publish_course' %}" id="publishCourse"  method="post" enctype="multipart/form-data"> {% csrf_token %}
	<button class="btn btn-outline-dark btn-lg float-right" type="button" id="publishCourseButton" onclick="publishCourse(this)" {% if not editCourse %} disabled {% endif %} >Publish</button>
</form>
{% endif %}
</nav>
<!--Warning message that course has been changed-->
<div id="addWarningMessage">
</div>
<div class="container">
		<div class="row my-2">
				<div class="col-lg-8 order-lg-2">
						<ul class="nav nav-tabs">
								{% if not editCourse and allChildCoursesCount and allChildCoursesCount > 0 %}
								<!-- <li class="nav-item">
									<a href="" data-target="#courseFromCourses" data-toggle="tab" 
									class= "nav-link" >From Existing Courses</a>
								</li> -->
								{% endif %}
								<li class="nav-item">
										<a href="" data-target="#courseDescription" data-toggle="tab" 
										class= {% if isCourseContent %} "nav-link" {% else %} "nav-link active" {% endif %} >Overview</a>
								</li>
								<li class="nav-item">
										<a href="" data-target="#addContent" data-toggle="tab" 
										class= {% if editCourse %} {% if isCourseContent %} "nav-link active" {% else %} "nav-link" {% endif %} {% else %} "nav-link disabled" {% endif %}>Videos</a>
								</li>
								{% if uploadMaterial  %}
 								<li class="nav-item">
									<a href="" data-target="#addMaterial" data-toggle="tab" 
									class= {% if isCourseContent %} "nav-link" {% else %} "nav-link active" {% endif %}>Material</a>
								</li>
								{% endif %}
						</ul>
						<div class="tab-content py-4">

								<div {% if isCourseContent %} class="tab-pane" {% else %} class="tab-pane active" {% endif %} id="courseDescription">
									<form action="{% url 'provider:create_course' %}" method="post" enctype="multipart/form-data"> {% csrf_token %}
										<div class="col-lg-3 order-lg-1 text-center">
												<img id="coursePic" src="{% thumbnail editCourse.picture|default:'default_profile.png' 100x100 crop %}" class="mx-auto img-fluid img-circle d-block" alt="avatar">
												<p>Upload Course Image</p>
												<input type="file" onchange="readURL(this,'coursePic');" class="form-control" name="course_pic">
												<hr>  
											  </div>
										<div class="form-row">
		  								<div class="col-md-4 mb-3">
												<label for="cName">Name</label>
												<input type="text" class="form-control" value= {% if editCourse %} "{{ editCourse.name }}" {% else %} "" {% endif %}
													name="courseName" id="cName" placeholder="Course Name" required>
											</div>
										<div class="col-md-4 mb-3">
											<label for="cExam">Exam</label>
											<select class="form-control" name="courseExam" id="cExam" onchange="fillSelectByName(this,'cSubject')" data-live-search="true" {% if editCourse and editCourse.exam != ""  %} readonly {% endif %} required>
												{% if editCourse and editCourse.exam != "" %}
												<option value="{{ editCourse.exam }}"selected>{{editCourse.exam}}</option>
												{% else %}
												<option value="">Exam</option>
												{% for x,y in allExams %}
												<option value="{{ x }}"{% if editCourse.exam == x %} selected{% endif %}>{{x}}</option>
											{% endfor %}
											{% endif %}
											</select>
										</div>
										{% if editCourse is None %}
										<div class="col-md-4 mb-3">
											<label for="cSubject">Subject(s)</label>
											<select class="form-control" name="courseSubject" id="cSubject" data-live-search="true" {% if editCourse and editCourse.subjects != "" %} disabled="true" {% endif %} required multiple>
												{% if editCourse and editCourse.subjects != "" %}
													{% if editCourseSubjects %}
														{% for subj in editCourseSubjects %}
														<option value="{{ editCourse.exam }}:{{ subj }}"selected>{{subj}}</option>
														{% endfor %}
													{% else %}
													<option value="{{ editCourse.exam }}:{{ editCourse.subjects }}"selected>{{editCourse.subjects}}</option>
													{% endif %}
												{% else %}
												<option value="">Subject(s)</option>
												
											{% for examKey,subjectVals in allSubjects.items  %}
												{% for subj in subjectVals %}
													{% if subj == editCourse.subjects %}
													<option value="{{ examKey }}:{{subj}}" selected>{{subj}}</option>
													{% endif %}
													{% if examKey != editCourse.exam %}
													<option value="{{ examKey }}:{{subj}}" hidden>{{subj}} </option>
													{% else %}
													<option value="{{ examKey }}:{{subj}}">{{subj}}</option>
													{% endif%}
												{% endfor %}
											{% endfor %}
											{% endif %}
											</select>
										</div>
										{% endif %}
								</div>
								<div class="form-row">
										<div class="col-md-4 mb-3">
												<label for="cSubjectOthers">Subject</label>
												<textarea class="form-control" name="courseSubjectOthers" id="cSubjectOthers" placeholder="Add Subject if Subject(s) is Others" rows="3"
												{% if editCourse %} disabled="true" {% endif %} >{% if editCourse %}{{editCourse.subjects}}{% endif %}</textarea>
											</div>
									<div class="col-md-8 mb-3">
										<label for="cDescription">Summary</label>
										<textarea class="form-control" name="courseDescription" id="cDescription" placeholder="Add Summary" rows="3">{% if editCourse %}{{editCourse.description}} {% endif %}</textarea>
									</div>
								</div>
								<div class="form-row">
										<div class="col-md-4 mb-2">
									<label for="cDuration">Duration (months)</label>
									<div class="input-group">
										<div class="input-group-prepend">
										<span class="input-group-text" id="inputGroupPrepend3">#</span>
										</div>
										<input type="number" class="form-control" value= {% if editCourse %} "{{ editCourse.duration }}" {% else %} 6 {% endif %}
										name="courseDuration" id="cDuration" placeholder="Duration" aria-describedby="cDuration" required>
									</div>
									</div>
									<div class="col-md-4 mb-2">
										<label for="cCost">Cost (INR)</label>
										<input type="number" class="form-control" value= {% if editCourse %} "{{editCourse.cost}}" {% else %} 10000 {% endif %}
										name="courseCost" id="cCost" placeholder="Cost" required>
									</div>
									 <div class="col-md-4 mb-2">
										<label for="cPublic">Visible to Purchase</label>
										<input type="checkbox" class="form-control md" {% if editCourse %} {% if editCourse.public == 1 %} checked {% endif %} {% else %} checked {% endif %}
										name="coursePublic" id="cPublic" >
									</div>
								</div>

									<input type="hidden" value= {% if editCourse.id %} "{{editCourse.id}}" {% endif %} name="courseId" />
									<button class="btn btn-primary" type="reset">Reset</button>
									<button id="toContent" class="btn btn-primary" type="submit">Proceed</button>
									</form>
								</div>
								<div {% if isCourseContent  %} class="tab-pane active" {% else %} class="tab-pane" {% endif %} id="addContent">
									{% include "create_content.html" %}	
								</div>
								<div class="tab-pane" id="courseFromCourses">
										{% include "create_courseFromCourses.html" %}		
								</div>
								<div {% if isCourseContent %} class="tab-pane" {% else %} class="tab-pane active" {% endif %} id="addMaterial">
									{% include "create_material.html" %}	
								</div>
						</div>
				</div>
		</div>
</div>
<script>
   function deleteMyCourse(el) {
        // first upload all lectures , then publish
		var hasStudents = "{{hasStudents}}";
		if (hasStudents == "true") {
			alert('Course has enrollments. Cant delete');
			return false;
		}
        if(!confirm('Do you want to delete this course ?')){
            return false;
        }
        $('#deleteMyCourse').submit();
        return true;
    }
	function clear_enrollments(el) {

        if(!confirm('Do you want to clear all enrollments of this course ? Students completed view hours will be lost!!')){
            return false;
        }
        $('#clear_enrollments').submit();
        return true;
    }

      function readURL(input,imgId) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#'+imgId)
                    .attr('src', e.target.result)
                    .width(100)
                    .height(100);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

</script>

{% endblock %}

eLearningCMS/src/provider/templates/upload_video_multiple.html
{% extends "__user_base.html" %}
{% load staticfiles %}
{% block active %}
<form action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<p>
		<input type="file" name="videos" multiple>
		<button type="submit">Upload</button>
	</p>
</form>
{% endblock active %}